Internal Server Error: /hangman/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/hangman/views.py", line 116, in hangman
    game.save()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "hangman_game" does not exist
LINE 1: INSERT INTO "hangman_game" ("user_id", "word", "current_gues...
                    ^

Internal Server Error: /hangman/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/hangman/views.py", line 116, in hangman
    game.save()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "hangman_game" does not exist
LINE 1: INSERT INTO "hangman_game" ("user_id", "word", "current_gues...
                    ^

Internal Server Error: /hangman/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/hangman/views.py", line 116, in hangman
    game.save()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "hangman_game" does not exist
LINE 1: INSERT INTO "hangman_game" ("user_id", "word", "current_gues...
                    ^

Internal Server Error: /hangman/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/hangman/views.py", line 116, in hangman
    game.save()
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "hangman_game" does not exist
LINE 1: INSERT INTO "hangman_game" ("user_id", "word", "current_gues...
                    ^

Not Found: /favicon.ico
Internal Server Error: /hangman/
Traceback (most recent call last):
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rebecca/Desktop/NerdStuff/Python/django-apptrack/apptrack/hangman/views.py", line 114, in hangman
    r = requests.get('http://randomword.setgetgo.com/get.php').lower()
AttributeError: 'Response' object has no attribute 'lower'
